### PR TITLE
Some optimizations

### PR DESCRIPTION
**Pull request by flbn**
To get the code coverage, change `<BRANCH_NAME>` to the `-`-separated branch name, e.g. `feature/added-hooks` --> `feature-added-hooks`

Coverage Badge

## Description

Removed the need for a couple of extra loops, though the overall Time Complexity remains `O(n^3)`. Also, instead of using the spread syntax, you can use `Array.from` to get some of that sweet, sweet JS Engine optimization.

## Motivation and Context

Just used this neat tool the other day and decided to contribute. 

## Related Issue

😭 doesn't exist, sorry!

## How Has This Been Tested?

`npm test` as well as comparing the demo to the original unchanged behavior.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Optimization and maintenance

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the contribution guidelines document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by flbn** [comment]
prettier fucked a lot of that PR up... lmk if you want a cleaner version without all of the syntax changes

**Comment by Minibrams** [comment]
Looks great, thanks for this 🚀 

I actually don't mind the prettier changes at all, but maybe you could include the prettierrc.json so we can keep the styling consistent for everyone?

**Comment by flbn** [comment]
added! cheers

**Comment by flbn** [comment]
sorry to bug but can we merge? potentially shipping something that's using the forked version, would be cool to just use the main one :)

**Comment by Minibrams** [comment]
Sorry for the wait, very busy week. Will take a final look and hopefully merge this evening. Thanks for this!

**Comment by flbn** [comment]
ahhh, sorry about that - feel free to wrap up whenever you can. had some weird anxiety it was forgotten. i can ship w the patch and replace later :)

**Comment by Minibrams** [comment]
Works great @flbn, awesome work 🚀

**Comment by Minibrams** [comment]
Optimizations released in [`svg-path-morph@1.0.3`](https://www.npmjs.com/package/svg-path-morph)

**Pull request merged**
